### ISSUE TITLE
jar not loaded offending class

### ISSUE THREAD

**Issue by robomotic** [KnowageLabs/Knowage-Server-Docker#10]
Related to the other issue for the Windows installer I am also getting this log (just marked as INFO):

> INFO: validateJarFile(C:\Program Files\Knowage\Knowage-Server-CE\webapps\knowagemeta\WEB-INF\lib\jsp-api-2.1.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class

Everything works though.

**Comment by aportosa** [comment]
Thanks for report this. It is not a bug indeed and it will not affect Knowage.
