### ISSUE TITLE
Docker tag for each released version

### ISSUE THREAD

**Issue by perezmlal** [KnowageLabs/Knowage-Server-Docker#14]
Please create a new **Docker tag** for each released version in https://github.com/KnowageLabs/Knowage-Server/releases **currently is 6.2.2**

Or at least in https://www.knowage-suite.com/site/knowage-download/ **currently is 6.2.1**

![knowage-suite com](https://user-images.githubusercontent.com/3089404/47985828-3bc49a00-e0db-11e8-9b90-aeb458695f17.png)

**Comment by kerny3d** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/6751879/78638068-ea11d780-78ab-11ea-8065-da9f0e75c402.png)
