### ISSUE TITLE
HTTP Status 404 - /knowagebirtreportengine/BirtReportServlet

### ISSUE THREAD

**Issue by piwi91** [KnowageLabs/Knowage-Server-Docker#2]
No engines are available in this Docker container.

```
root@85623567d1d8:/home/knowage/apache-tomcat-7.0.57/webapps# ls
COPYING  LICENSE.txt  ROOT  docs  examples  host-manager  knowage  manager
```

EDIT: Only in tag `6.1`. Tag `develop` does have the engines.

**Comment by aportosa** [comment]
Sorry, we are in process on release Knowage version 6.1.1.
For now, I left only the develop version. I will re-enable the 6.1.1 version as soon as it will be released.
