### ISSUE TITLE
knowage and keyrock

### ISSUE THREAD

**Issue by SamuelTJackson** [KnowageLabs/Knowage-Server-Docker#24]
Hey,
knowage and keyrock are not working for me, because knowage is not sending a state variable.

As mentioned [here](https://www.knowage-suite.com/qa/2681/sso-knowage-%26-keyrock?show=2681#q2681) I set the redirect URL to `https://knowage.mydomain/knowage/servlet/AdapterHTTP?PAGE=LoginPage`

In my browser I go to `https://knowage.mydomain/knowage` and get redirected to
`https://keyrock.mydomain.de/oauth2/authorize?response_type=code&client_id=68d6e050-6037-40a7-ba1b-9ed4570b409d&redirect_uri=https%3A%2F%2Fknowage.mydomain%2Fknowage%2Fservlet%2FAdapterHTTP%3FPAGE%3DLoginPage`

After authorizing knowage to read my public information from keyrock, keyrock shows me an error:
```
OAuth2 request has failed!
error - Missing parameter: `state`
```
I'm using:
knowagelabs/knowage-server-docker:7.0
fiware/idm:FIWARE_7.8

Extract from configs.properties:
```
AUTHORIZE_URL=https://keyrock.mydomain.de/oauth2/authorize
ACCES_TOKEN_URL=https://keyrock.mydomain/oauth2/token
USER_INFO_URL=https://keyorck.mydomain/user
REDIREKT_URI=https://knowage.mydomain/knowage/servlet/AdapterHTTP?PAGE=LoginPage
REST_BASE_URL=https://keyrock.mydomain.de
```

**Comment by ape-lazy** [comment]
Even I'm stuck here!! what solution was applied here? Please help

**Comment by ape-lazy** [comment]
> Even I'm stuck here!! what solution was applied here? Please help

Okay, I tackled this by adding "STATE=true" to config.properties
