### ISSUE TITLE
Install Konwage 7.0 using docker-compose

### ISSUE THREAD

**Issue by RABEB2** [KnowageLabs/Knowage-Server-Docker#26]
does anyone succeed to install knowage server 7.0 using docker compose please ? 

here is my docker-compose file 

`version: "3.1"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.0
    depends_on:
      - knowagedb
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - WAIT_MYSQL=true
      - DB_USER=knowageuser
      - DB_PASS=knowagepassword
      - DB_DB=knowagedb
      - DB_HOST=localhost
      - DB_PORT=3306
      - HMAC_KEY=abc123
      - PUBLIC_ADDRESS=localhost
 
  knowagedb:
    image: mysql:5.7
    environment:
      - MYSQL_USER=rabeb
      - MYSQL_PASSWORD=rabeb
      - MYSQL_DATABASE=noor_it
      - MYSQL_ROOT_PASSWORD=
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:

networks:
  main:`

can anyone help me please

**Comment by kerny3d** [comment]
`MYSQL_ROOT_PASSWORD` env is mandatory.

From logs you can see:
`[Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.`
`[Note] [Entrypoint]: Switching to dedicated user 'mysql'`
`[Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.`
`[ERROR] [Entrypoint]: Database is uninitialized and password option is not specified. You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD`

**Comment by RABEB2** [comment]
thank u for ur reply 
while starting containers 
i got this error 
**knowage_1    | ERROR 1045 (28000): Access denied for user 'knowageuser'@'172.19.0.3' (using password: YES)**

![image (1)](https://user-images.githubusercontent.com/28419584/69535740-da3ccb00-0f7c-11ea-9e93-6c8d4e3ec9a8.png)


can u help me please ?

**Comment by kerny3d** [comment]
`DB_USER` need to have the same value of `MYSQL_USER`, `DB_PASS` the same as `MYSQL_PASSWORD`, `DB_DB` the same as `MYSQL_DATABASE`.

Watch out for `DB_HOST`: if you use Docker Compose to run the db, this needs to have a value equals to the name of the MySql container; in your case, it's probably `knowagedb`.

See our [example docker-compose.yml](https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/docker-compose.yml) and the fundamental [.env file](https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/.env), used to define the env vars needed by both containers.

**Comment by kerny3d** [comment]
I'm closing the issue due to inactivity.
