### ISSUE TITLE
support the Chinese

### ISSUE THREAD

**Issue by Hello-Linux** [KnowageLabs/Knowage-Server-Docker#29]
I hope knowage can support the Chinese,Because so many people in China want to use it。After all, this is a very good BI analysis tool. I hope it can be widely used in other countries so that more and more people can use it.

**Comment by Redjaw** [comment]
Hi, at the moment there is an incomplete Chinese translation for Knowage in Zanata.
You can participate too signing in to the Knowage Zanata project here: [Zanata](https://www.knowage-suite.com/zanata/)
We are also creating the configurations for the many dialects so it will be released soon.
