### ISSUE TITLE
SSL+Port Issue Public Address

### ISSUE THREAD

**Issue by TobiasHauck** [KnowageLabs/Knowage-Server-Docker#33]
Hi guys,

I'm running knowage behind a reverse proxy (traefik) with SSL certificate and auto-redirect from 80 to port 443. In general that's working well, but a few links don't work any more, for example editing the fields of an imported csv-file (add dataset file type, upload, click next -> error). The error says that it wants to open an URL in the format:

```http://my-domain:8080/knowage```

But it should open an url in the format:

```
https://my-domain/knowage
```

The reason for that seems to be that the entrypoint.sh doesn't change the protocol and port of the public addresses in the server.xml.

https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/entrypoint.sh#L41

Adding ENV vars for protocol and port would be a small fix with a big impact I believe.

**Comment by kerny3d** [comment]
Hi @TobiasHauck,

we know that this is a big limitation for Knowage behind a reverse proxy or a load balancer. For the 7.2 release I'm testing the option to let the user to set the entire URL. We would know how other projects here on GitHub fixed this problem: if you know someone we will try to replicate the fix here.

In the meantime, the workaround is very simple: mount server.xml as volume with the correct host_url and overwrite the entrypoint to prevent entrypoint.sh to be executed.
