### ISSUE TITLE
Docker image _manifest unknown_ error

### ISSUE THREAD

**Issue by adrienandrem** [KnowageLabs/Knowage-Server-Docker#34]
`docker-compose up` command fails:

```
$ docker-compose up
Pulling knowage (knowagelabs/knowage-server-docker:7.2)...
ERROR: manifest for knowagelabs/knowage-server-docker:7.2 not found: manifest unknown: manifest unknown
```

**Comment by kerny3d** [comment]
Hi @adrienandrem, we are working on it and it will be available soon.

You can follow the progress on the master branch.

**Comment by kerny3d** [comment]
Hi @adrienandrem, knowage-server-docker:7.2 available.

**Comment by adrienandrem** [comment]
@kerny3d confirming image pull works here, thanks!
