### ISSUE TITLE
ERROR: manifest for knowagelabs/knowage-server-docker:7.2 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by viju2008** [KnowageLabs/Knowage-Server-Docker#35]
#docker compose up
Creating network "knowage-server-docker_main" with the default driver
Creating volume "knowage-server-docker_db" with default driver
Pulling knowagedb (mariadb:10.3)...
10.3: Pulling from library/mariadb
d72e567cc804: Pull complete
0f3630e5ff08: Pull complete
b6a83d81d1f4: Pull complete
4bf2111ecf0e: Pull complete
9572d64978a0: Pull complete
bcc9953bffb3: Pull complete
de429570dda5: Pull complete
3652bc6ea9f9: Pull complete
6e4bf87041c8: Pull complete
d19e8769b9aa: Pull complete
7a8060bddcd6: Pull complete
ef5d7c679358: Pull complete
c1220fea18c8: Pull complete
Digest: sha256:5adbf9e5943d260914a4821c91fae0e0287d24fdb21b8c8ee7e6529a81d0b9b2
Status: Downloaded newer image for mariadb:10.3
Pulling knowage (knowagelabs/knowage-server-docker:7.2)...
ERROR: manifest for knowagelabs/knowage-server-docker:7.2 not found: manifest unknown: manifest unknown

**Comment by kerny3d** [comment]
Hi @viju2008, knowage-server-docker:7.2 available.

**Comment by viju2008** [comment]
I tried with the same version
