### ISSUE TITLE
Knowage server can't connect to MySQL

### ISSUE THREAD

**Issue by miro63** [KnowageLabs/Knowage-Server-Docker#36]
I have installed Knowage-Server-Docker on Docker Desktop Win 10 P and Maria DB and Knowage-Python are running  on their containers I have used last versions of compose file for docker server.
The Knowage server doen't want to run, it starts and after few seconds stops. The message as below.

> wait-for-it.sh: waiting 15 seconds for localhost:3306
> wait-for-it.sh: timeout occurred after waiting 15 seconds for localhost:3306
> MySql is up!
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Where could be the problem?

**Comment by miro63** [comment]
I have found solution

**Comment by bitsnaps** [comment]
> I have found solution

I'm running into the same issue, how did fix it?
