### ISSUE TITLE
How to update knowage use docker?

### ISSUE THREAD

**Issue by Hello-Linux** [KnowageLabs/Knowage-Server-Docker#37]
How to update know use docker? I what update knowage version 6.4.5 to 7.2.6

**Comment by kerny3d** [comment]
Hi,

there is no automatic update. You need to update both the image and the DB manually.

For the DB, please look at:

https://github.com/KnowageLabs/Knowage-Server/tree/master/knowagedatabasescripts

In every directory you can find all the updating scripts for your DB.
