### ISSUE TITLE
About Knowage Kubernetes deployment information, example and tutorial ?

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#39]
Hello, 
We have a project which uses some **Fiware GEs**, among them **Knowage**, but where containers are deployed on a **Kubernetes** cluster. 

And we have several questions about Knowage and Kubernetes, since we didn't found any information by googling :

- Have you something in your roadmap about documenting deployment with Kubernetes ?
- Can you provide some advice to achieve deployment with K8S ? 
- We have the idea to use [Kompose](https://kompose.io/) to transform the docker compose or stack file, is it a good solution ?

Thanks in advance for your feedback

**Comment by kerny3d** [comment]
We will work on Kubernetes in the next months.

Now, there is only one of my personal repo:

https://github.com/kerny3d/Knowage-Kubernetes

N.B.: there isn't the cache DB, i hope to add it in the next days.

**Comment by agaldemas** [comment]
Thanks for your kind answer and link to your repo, CU
