### ISSUE TITLE
Sample Knowage docker-compose.yml File?

### ISSUE THREAD

**Issue by weekaung** [KnowageLabs/Knowage-Server-Docker#41]
Hello All,
I cannot seem to be able to startup the Knowage docker image. 
The documentation seems to not have enough details to start it up or is it my problem.
Do anyone have a working docker-compose.yml file that I can use?
Thanks.

**Comment by kerny3d** [comment]
Hi,

have a look at the official docker-compose descriptor into Knowage-Server-Docker directory.

https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/Knowage-Server-Docker/docker-compose.yml

You will find also the README.md for the main image.

**Comment by weekaung** [comment]
Thank you so much. I will look into it.
