### ISSUE TITLE
docker build fails to copy knowage-database-scripts-mysql.zip and war files

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server-Docker#42]
# Hello,

I'm trying to build myself docker image using `Knowage-Server-Docker/dockerfile`  , but it fails, because of missing knowage-database-scripts-mysql.zip here is the error :

```
Step 44/72 : COPY ${KNOWAGE_DATABASE_SCRIPT}.zip ./
COPY failed: stat /var/lib/docker/tmp/docker-builder043376001/knowage-database-scripts-mysql.zip: no such file or directory
```

How is the knowage-database-scripts-mysql.zip prepared and retrieved ?, it should be in the repo, but no ?

Most probably the zip is prepared from Knowage-Server repositor directory, [knowagedatabasescripts/mysql](https://github.com/KnowageLabs/Knowage-Server/tree/master/knowagedatabasescripts/mysql)
so I made manually a zip file and copy it...
But after no war files found : 

```
Step 46/72 : COPY ${KNOWAGE_CORE_ENGINE}.war      ${KNOWAGE_BIRTREPORT_ENGINE}.war      ${KNOWAGE_COCKPIT_ENGINE}.war      ${KNOWAGE_COMMONJ_ENGINE}.war      
${KNOWAGE_GEOREPORT_ENGINE}.war      ${KNOWAGE_JASPERREPORT_ENGINE}.war      ${KNOWAGE_KPI_ENGINE}.war
${KNOWAGE_META_ENGINE}.war      ${KNOWAGE_QBE_ENGINE}.war      ${KNOWAGE_SVGVIEWER_ENGINE}.war      ${KNOWAGE_TALEND_ENGINE}.war      ${KNOWAGE_WHATIF_ENGINE}.war      ${TOMCAT_WEBAPPS}/
COPY failed: stat /var/lib/docker/tmp/docker-builder238311328/knowage.war: no such file or directory
```

Thanks in advance to give hint on how to prepare files from [Knowage-server](https://github.com/KnowageLabs/Knowage-Server) repository to build the image

**Comment by kerny3d** [comment]
Hi agaldemas,

if you take a look at:

https://github.com/KnowageLabs/Knowage-Server/blob/master/knowagedatabasescripts/pom.xml

You can see that the knowagedatabasescripts is a Maven project that produces just the artifact you need. In <plugins> you can find all the packages we build at package phase.

**Comment by agaldemas** [comment]
Thank for your answer @kerny3d
