### ISSUE TITLE
Error execute docker-compose.yml Knowage-Server-Docker 7.4

### ISSUE THREAD

**Issue by mvits** [KnowageLabs/Knowage-Server-Docker#49]
I have a problem with execute docker-compose, because return message : 
"Cannot create container for service knowage: invalid volume specification: '658f544afdeacde4f48bedd5b206a2f9a34e573b2b6ea1fe96506c68dcdd44ed:[/home/knowage/apache-tomcat/resources]:rw': invalid mount config for type "volume": invalid mount path: '[/home/knowage/apache-tomcat/resources]' mount path must be absolute

ERROR: for knowage  Cannot create container for service knowage: invalid volume specification: '658f544afdeacde4f48bedd5b206a2f9a34e573b2b6ea1fe96506c68dcdd44ed:[/home/knowage/apache-tomcat/resources]:rw': invalid mount config for type "volume": invalid mount path: '[/home/knowage/apache-tomcat/resources]' mount path must be absolute
ERROR: Encountered errors while bringing up the project."

My docker-compose contains: 

version: "3.1"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.4.0-SNAPSHOT
    depends_on:
      - knowagedb
      - knowagecache
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - DB_HOST=knowagedb
      - DB_PORT=3306
      - DB_DB=knowagedb
      - DB_USER=knowageuser
      - DB_PASS=knowagepassword

      - CACHE_DB_HOST=knowagecache
      - CACHE_DB_PORT=3306
      - CACHE_DB_DB=knowagedb
      - CACHE_DB_USER=knowageuser
      - CACHE_DB_PASS=knowagepassword

      - HMAC_KEY=abc123
      - PASSWORD_ENCRYPTION_SECRET=def456
      - PUBLIC_ADDRESS=localhost
     
  knowagepython:
    image: knowagelabs/knowage-python-docker:7.4
    environment:
      - HMAC_KEY=abc123
      - KNOWAGE_PUBLIC_ADDRESS=knowage
      - PUBLIC_ADDRESS=localhost
    networks:
      - main

  knowager:
    image: knowagelabs/knowage-r-docker:7.4
    environment:
      - HMAC_KEY=abc123
    networks:
      - main

  knowagedb:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=knowageuser
      - MYSQL_PASSWORD=knowagepassword
      - MYSQL_DATABASE=knowagedb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"

  knowagecache:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=knowageuser
      - MYSQL_PASSWORD=knowagepassword
      - MYSQL_DATABASE=knowagedb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - main
    volumes:
      - "cache:/var/lib/mysql"

volumes:
  db:
  cache:

Also I work other example with volumen : 

version: "3.1"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:7.4
    depends_on:
      - knowagedb
      - knowagecache
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - DB_HOST=knowagedb
      - DB_PORT=3306
      - DB_DB=knowagedb
      - DB_USER=knowageuser
      - DB_PASS=knowagepassword

      - CACHE_DB_HOST=knowagecache
      - CACHE_DB_PORT=3306
      - CACHE_DB_DB=knowagedb
      - CACHE_DB_USER=knowageuser
      - CACHE_DB_PASS=knowagepassword

      - HMAC_KEY=abc123
      - PASSWORD_ENCRYPTION_SECRET=def456
      - PUBLIC_ADDRESS=localhost
   volumes:
      - "data:/home/knowage/apache-tomcat/resources" 
  knowagepython:
    image: knowagelabs/knowage-python-docker:7.4
    environment:
      - HMAC_KEY=abc123
      - KNOWAGE_PUBLIC_ADDRESS=knowage
      - PUBLIC_ADDRESS=localhost
    networks:
      - main

  knowager:
    image: knowagelabs/knowage-r-docker:7.4
    environment:
      - HMAC_KEY=abc123
    networks:
      - main

  knowagedb:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=knowageuser
      - MYSQL_PASSWORD=knowagepassword
      - MYSQL_DATABASE=knowagedb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"

  knowagecache:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=knowageuser
      - MYSQL_PASSWORD=knowagepassword
      - MYSQL_DATABASE=knowagedb
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - main
    volumes:
      - "cache:/var/lib/mysql"

volumes:
  db:
  cache:
  data:
networks:
  main:

networks:
  main:

Any known solution ?

**Comment by bendraaisma** [comment]
I have the same issue, and it looks like the example docker-compose file is missing the volume setup for the tomcat resource directory. 

You can see in this link https://github.com/KnowageLabs/Knowage-Server-Docker/issues/38#issuecomment-748805625 how to set it up in your own compose file.

**Comment by kerny3d** [comment]
Hi all,

I confirm we forgot to put an example on our docker-compose files but at least we put the declaration in the Dockerfile:

https://github.com/KnowageLabs/Knowage-Server-Docker/blob/knowage-server-7.4/Knowage-Server-Docker/Dockerfile#L166

I'll fix the docker-compose files in the next days.

Please remember that we have updated the 7.4 image some time ago: please remember to pull or at least to check the hash.

**Comment by mvits** [comment]
Thanks, for your help.
